In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
a[0]

1

In [9]:
b = np.arange(10)

In [10]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
c = np.arange(1, 10, 2)

In [12]:
c

array([1, 3, 5, 7, 9])

In [15]:
d = np.arange(10, 210, 10).reshape((4,5))

In [16]:
d

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [19]:
e = np.array([[2,4,6,8,10], [10, 20, 30, 40, 50]])
e

array([[ 2,  4,  6,  8, 10],
       [10, 20, 30, 40, 50]])

In [20]:
f = np.array([
                [[20, 30, 40], [50, 60, 70]],
                [[10, 20, 30], [40, 50, 60]],
             ])

In [21]:
f

array([[[20, 30, 40],
        [50, 60, 70]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [22]:
f.shape

(2, 2, 3)

In [23]:
f.ndim

3

In [24]:
f.size           # total items 

12

In [25]:
f.itemsize        # total no of rows

4

In [26]:
f.nbytes           # total bytes to stores array

48

In [29]:
f[1, 1, 1]

50

In [30]:
f[1, -1, -2]

50

In [34]:
f[:, 1, 0]

array([50, 40])

Zeros

In [39]:
g = np.zeros((2,3), dtype = np.int32)        # dtype = "int32"  (we can also write it in this way)
g

array([[0, 0, 0],
       [0, 0, 0]])

Ones


In [41]:
np.ones((3, 2, 4), dtype = "int32")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [42]:
np.full((2,4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

In [43]:
np.random.rand(2, 4)

array([[0.24990123, 0.53448005, 0.3217646 , 0.14168682],
       [0.12742689, 0.44252734, 0.71287363, 0.40384401]])

In [47]:
np.random.randint(50, size=(2,4))        # (end, size)

array([[11, 41, 11, 41],
       [45, 29, 15,  9]])

In [48]:
np.random.randint(50, 100, size=(2,4))        # (start, end, size)

array([[51, 93, 57, 68],
       [71, 91, 52, 84]])

In [51]:
np.identity(4, dtype="int16")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [54]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
b = a.copy()
b[0, 0] = 100
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100   1   2   3   4]
 [  5   6   7   8   9]]


In [57]:
b += 2 
print(b)

[[102   3   4   5   6]
 [  7   8   9  10  11]]


In [58]:
b *= 2
print(b)

[[204   6   8  10  12]
 [ 14  16  18  20  22]]


In [64]:
c = np.array([100, 100, 100, 100, 100])
print(a)
a = a + c
print(a)

[[ 400  701 1002 1303 1604]
 [ 405  706 1007 1308 1609]]
[[ 500  801 1102 1403 1704]
 [ 505  806 1107 1408 1709]]
